name: 'grid'
is_discrete: True
is_diff_drive: False
num_agents: 2
map_size: 30
max_vel: 0.03
min_vel: -0.01
max_ang_vel: 0.25
min_ang_vel: -0.25
max_acc: 0.015
max_ang_acc: 0.125
fov_r: 3
comm_r: 4
num_scans: 64
scan_range: 0.1
use_intentions: True
level: 5
timeout: 100
rad: 0.02
goal_rad: 0.02
goal_reward: 3
crash_penalty: -10
time_penalty: -0.1
obs_type: "random"
sample_type: "uniform"
obs_size_lower_bound: 0.05
obs_size_upper_bound: 0.08