# learnig parameters
horizon: 1000000
gamma: 0.95
tau: 0.005
target_entropy_ratio: 0.05
batch_size: 256
auto_temp_tuning: True
save_interval: 100000
warmup_iters: 10000
# buffer
capacity: 1500000
use_per: False
# evaluate
eval_iters: 1000